server:
  port: 8087

spring:
  application:
    name: billing-service

  datasource:
    url: jdbc:mysql://localhost:3306/healthcare_billing_db
    username: root
    password: Malli@160902

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
